=== chenxuehu2016/phxrpc/svrkit.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="svrkit">
        <xs:annotation>
            <xs:documentation>sudo apt install libxml2-utils; xmllint &amp;amp;#45;&amp;amp;#45;noout &amp;amp;#45;&amp;amp;#45;schema ../schema.xsd phxbinlogsvr.xml</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pkgs">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded" minOccurs="0">
                            <xs:element name="pkg" maxOccurs="unbounded" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>vpath %.proto $(SRC_BASE_PATH)/phxbinlogsvr/framework/protophxrpc_phxbinlog_stub.cpp:phxbinlogsvr.proto$(PHXRPC_INCLUDE_PATH)/codegen/phxrpc_pb2client -f phxbinlogsvr.proto -I $(SRC_BASE_PATH)/phxbinlogsvr/framework/proto/ -I $(PROTOBUF_INCLUDE_PATH) -d .vpath %.proto $(SRC_BASE_PATH)/phxbinlogsvr/framework/protophxrpc_phxbinlog_dispatcher.cpp:phxbinlogsvr.proto$(PHXRPC_INCLUDE_PATH)/codegen/phxrpc_pb2service -f phxbinlogsvr.proto -I $(SRC_BASE_PATH)/phxbinlogsvr/framework/proto/ -I $(PROTOBUF_INCLUDE_PATH) -d .phxrpc_phxbinlog_service.cpp:phxbinlogsvr.proto$(PHXRPC_INCLUDE_PATH)/codegen/phxrpc_pb2service -f phxbinlogsvr.proto -I $(SRC_BASE_PATH)/phxbinlogsvr/framework/proto/ -I $(PROTOBUF_INCLUDE_PATH) -d .vpath %.proto $(SRC_BASE_PATH)/phxbinlogsvr/framework/protophxrpc_phxbinlog_tool.cpp:phxbinlogsvr.proto$(PHXRPC_INCLUDE_PATH)/codegen/phxrpc_pb2tool -f phxbinlogsvr.proto -I $(SRC_BASE_PATH)/phxbinlogsvr/framework/proto/ -I $(PROTOBUF_INCLUDE_PATH) -d .</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="lib" maxOccurs="unbounded" minOccurs="0">
                                            <xs:annotation>
                                                <xs:documentation>PHXBINLOGCONFIG_LIB=phxbinlogconfig phxcomm/configparser:phxconfig phxcomm/utils:phxutils include:phxcomm_include</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <xs:element name="syslib">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="prefix" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="inc" maxOccurs="unbounded" minOccurs="0">
                                            <xs:annotation>
                                                <xs:documentation>PHXBINLOGCONFIG_INCS=$(SRC_BASE_PATH)/phxbinlogsvr/config</xs:documentation>
                                            </xs:annotation>
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="prefix" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="extra-cppflags">
                                            <xs:annotation>
                                                <xs:documentation>PHXBINLOGCONFIG_EXTRA_CPPFLAGS=-Wall</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                        <!--<xs:element name="vpath" minOccurs="0">-->
                                            <!--<xs:complexType>-->
                                                <!--<xs:simpleContent>-->
                                                    <!--<xs:extension base="xs:string">-->
                                                        <!--<xs:attribute type="xs:string" name="prefix" use="optional"/>-->
                                                    <!--</xs:extension>-->
                                                <!--</xs:simpleContent>-->
                                            <!--</xs:complexType>-->
                                        <!--</xs:element>-->
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name" use="optional"/>
                                    <xs:attribute type="xs:string" name="hinc" use="optional"/>
                                    <xs:attribute type="xs:string" name="cfiles" use="optional"/>
                                    <xs:attribute type="xs:string" name="type" use="optional"/>
                                    <xs:attribute type="xs:string" name="phxrpc" use="optional"/>
                                    <xs:attribute type="xs:string" name="protobuf-ref" use="optional"/>
                                    <xs:attribute type="xs:string" name="hmvfiles" use="optional" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="src-list">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="dir" maxOccurs="unbounded" minOccurs="0"/>
                                        <xs:element type="xs:string" name="lib" minOccurs="0"/>
                                        <xs:element type="xs:string" name="syslib" minOccurs="0"/>
                                        <xs:element name="inc" minOccurs="0">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="prefix" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="extra-cppflags" minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name" use="optional"/>
                                    <xs:attribute type="xs:string" name="type" use="optional"/>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="protobuf">
                                <xs:annotation>
                                    <xs:documentation>http://lenya.apache.org/docu12x/misc/xinclude.html</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ref" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="file" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name" use="required"/>
                                    <xs:attribute type="xs:string" name="dir" use="required"/>
                                    <xs:attribute type="xs:string" name="file" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== chenxuehu2016/phxrpc/svrkit.xml
<?xml version="1.0"?>
<!--sudo apt install libxml2-utils; xmllint &#45;&#45;noout &#45;&#45;schema ./svrkit.xsd svrkit.xml-->
<svrkit   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./svrkit.xsd">
    <pkgs>
        <pkg name="phxbinlogsvr/config:phxbinlogconfig" hinc="include/phxbinlogsvr/config"
             cfiles="phxbinlog_svr_base_config, phxsql_config, phxbinlog_config">
            <!--PHXBINLOGCONFIG_LIB=phxbinlogconfig phxcomm/configparser:phxconfig phxcomm/utils:phxutils include:phxcomm_include-->
            <lib>phxbinlogconfig</lib>
            <lib>phxcomm/configparser:phxconfig</lib>
            <lib>phxcomm/utils:phxutils</lib>
            <lib>include:phxcomm_include</lib>
            <syslib></syslib>
            <!--PHXBINLOGCONFIG_INCS=$(SRC_BASE_PATH)/phxbinlogsvr/config-->
            <inc prefix="$(SRC_BASE_PATH)">phxbinlogsvr/config</inc>
            <!--PHXBINLOGCONFIG_EXTRA_CPPFLAGS=-Wall-->
            <extra-cppflags>-Wall</extra-cppflags>
        </pkg>

        <pkg name="phxbinlogsvr/core/agent:agent" cfiles="agent, agent_manager, data_manager">
            <lib>agent</lib>
            <lib>phxcomm/log/phxlog:phxlog</lib>
            <lib>phxbinlogsvr/config:phxbinlogconfig</lib>
            <lib>phxbinlogsvr/core/monitor:agentmonitor</lib>
            <lib>phxbinlogsvr/core/paxos:eventagent</lib>
            <lib>phxbinlogsvr/core/paxos:masteragent</lib>
            <lib>phxbinlogsvr/core/repl:agentrepl</lib>
            <syslib></syslib>
            <inc prefix="$(SRC_BASE_PATH)">phxbinlogsvr/core/agent</inc>
            <inc prefix="$(SRC_BASE_PATH)">phxbinlogsvr/core</inc>
            <extra-cppflags>-Wall -Werror</extra-cppflags>
        </pkg>

        <pkg name="phxbinlogsvr/framework/phxrpc/client:phxbinlogsvrclient_phxrpc"
             type="elib" phxrpc="client" protobuf-ref="phxbinlog">
            <lib>phxbinlogsvrclient_phxrpc</lib>
            <lib>phxbinlogsvr/framework/rpccomm:phxbinlogsvrclient_base</lib>
            <lib>phxbinlogsvr/framework/proto:clientproto</lib>
            <lib>phxbinlogsvr/core/mysql:gtidhandler</lib>
            <lib>include:phxcomm_include</lib>
            <syslib prefix="$(PHXRPC_LIB_PATH)">libphxrpc.a</syslib>
            <inc prefix="$(SRC_BASE_PATH)">phxbinlogsvr/framework/phxrpc/client</inc>
            <inc prefix="$(PHXRPC_INCLUDE_PATH)"></inc>
            <extra-cppflags>-Wall</extra-cppflags>
        </pkg>

        <pkg name="phxbinlogsvr/framework/phxrpc/svr:phxbinlogsvr_phxrpc"
             type="bin" phxrpc="svr" protobuf-ref="phxbinlog">
            <lib>phxbinlogsvr/framework/phxrpc/client:phxbinlogsvrclient_phxrpc</lib>
            <lib>phxbinlogsvr/framework/rpccomm:phxbinlogsvrlogic</lib>
            <lib>phxcomm/log/phxglog:phxglog</lib>
            <syslib prefix="$(PHXRPC_LIB_PATH)">libphxrpc.a</syslib>
            <inc prefix="$(SRC_BASE_PATH)">phxbinlogsvr/framework/phxrpc/svr</inc>
            <inc prefix="$(PHXRPC_INCLUDE_PATH)"></inc>
            <extra-cppflags>-Wall</extra-cppflags>
        </pkg>

        <pkg name="phxbinlogsvr/framework/phxrpc/tools:phxbinlogsvr_tools_phxrpc"
             type="bin" phxrpc="tools" protobuf-ref="phxbinlog">
            <lib>phxbinlogsvr/framework/phxrpc/client:phxbinlogsvrclient_phxrpc</lib>
            <syslib prefix="$(PHXRPC_LIB_PATH)">libphxrpc.a</syslib>
            <inc prefix="$(SRC_BASE_PATH)">phxbinlogsvr/framework/phxrpc/tools</inc>
            <inc prefix="$(PHXRPC_INCLUDE_PATH)"></inc>
            <extra-cppflags>-Wall</extra-cppflags>
        </pkg>

        <pkg name="phxbinlogsvr/framework/proto:clientproto" phxrpc="protobuf"
             protobuf-ref="phxbinlog">
            <lib>clientproto</lib>
            <syslib prefix="$(PROTOBUF_LIB_PATH)">libprotobuf.a</syslib>
            <inc prefix="$(SRC_BASE_PATH)">phxbinlogsvr/framework/proto</inc>
            <inc prefix="$(PROTOBUF_INCLUDE_PATH)"></inc>
            <extra-cppflags>-Wall</extra-cppflags>
        </pkg>

        <!--http://lenya.apache.org/docu12x/misc/xinclude.html-->
        <protobuf name="phxbinlog" dir="phxbinlogsvr/framework/proto" file="phxbinlogsvr.proto">
            <ref file="./phxbinlogsvr.xml"/>
        </protobuf>

        <src-list name="phxbinlogsvr">
            <dir>proto</dir>
            <dir>config</dir>
            <dir>core</dir>
            <dir>framework</dir>
        </src-list>

        <pkg name="include:phxcomm_include"
             type="elib">
            <lib></lib>
            <syslib></syslib>
            <inc prefix="$(SRC_BASE_PATH)">include</inc>
            <extra-cppflags>-Wall</extra-cppflags>
        </pkg>

        <pkg name="include/phxbinlogsvr:phxbinlogsvr_include"
             type="elib">
            <lib></lib>
            <syslib></syslib>
            <inc prefix="$(SRC_BASE_PATH)">include/phxbinlogsvr</inc>
            <extra-cppflags>-Wall</extra-cppflags>
        </pkg>

    </pkgs>
</svrkit>

=== chenxuehu2016/phxrpc/svrkit-phxpaxos.xml
<?xml version="1.0"?>
<!--sudo apt install libxml2-utils; xmllint &#45;&#45;noout &#45;&#45;schema ./svrkit.xsd svrkit.xml-->
<svrkit  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./svrkit.xsd">

    <pkgs>
        <pkg name="src/algorithm:algorithm"
             cfiles="base, proposer,acceptor,learner,learner_sender,instance,ioloop,commitctx,committer,checkpoint_sender,checkpoint_receiver,msg_counter">
            <lib>algorithm</lib>
            <lib>src/comm:comm</lib>
            <lib>src/logstorage:logstorage</lib>
            <lib>src/sm-base:smbase</lib>
            <lib>include:include</lib>
            <lib>src/checkpoint:checkpoint</lib>
            <lib>src/config:config</lib>
            <syslib></syslib>
            <inc prefix="$(SRC_BASE_PATH)">src/algorithm</inc>
            <extra-cppflags>-Wall -Werror</extra-cppflags>
        </pkg>

        <pkg name="src/communicate:communicate"  hinc="include/phxpaxos" hmvfiles="network"
             cfiles="dfnetwork,udp,network,communicate">
            <lib>communicate</lib>
            <lib>src/utils:utils</lib>
            <lib>src/comm:comm</lib>
            <lib>src/config:config</lib>
            <lib>include:include</lib>
            <lib>src/communicate/tcp:communicate_tcp</lib>
            <syslib></syslib>
            <inc prefix="$(SRC_BASE_PATH)">src/communicate</inc>
            <extra-cppflags>-Wall -Werror</extra-cppflags>
        </pkg>

        <pkg name="src/communicate/tcp:communicate_tcp"
             cfiles="event_base,message_event,event_loop,tcp_client,tcp_acceptor,notify,tcp">
            <lib>communicate_tcp</lib>
            <lib>src/utils:utils</lib>
            <lib>include:include</lib>
            <lib>src/comm:comm</lib>
            <syslib></syslib>
            <inc prefix="$(SRC_BASE_PATH)">src/communicate/tcp</inc>
            <extra-cppflags>-Wall -Werror</extra-cppflags>
        </pkg>

        <pkg name="include:include">
            <lib></lib>
            <syslib></syslib>
            <inc prefix="$(SRC_BASE_PATH)">include</inc>
            <extra-cppflags>-Wall -Werror</extra-cppflags>
        </pkg>

        <pkg name=":phxpaxos" type="elib">
            <lib>src/node:node</lib>
            <lib>include:include</lib>
            <syslib></syslib>
            <inc prefix="$(SRC_BASE_PATH)"></inc>
            <extra-cppflags>-Wall -Werror</extra-cppflags>
        </pkg>
    </pkgs>
</svrkit>
